#!/usr/bin/env node
// Regenerates /STATUS.md, the generated (never hand-edited) traceability
// matrix: requirement -> citing tests -> uncited flag, per spec file. See
// specs/README.md's "Generated status" section.
//
// Usage:
//   node scripts/gen-status.mjs           # writes STATUS.md
//   node scripts/gen-status.mjs --check   # exits 1 if STATUS.md is stale
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parseSpecs, scanTestCitations } from "./check-drift.mjs";

export function generateStatus(rootDir) {
  const { registry } = parseSpecs(join(rootDir, "specs"));
  const citations = scanTestCitations(rootDir);

  const byFile = new Map();
  for (const [id, info] of registry) {
    if (!byFile.has(info.file)) byFile.set(info.file, []);
    byFile.get(info.file).push({ id, ...info });
  }

  const lines = [];
  lines.push("# STATUS");
  lines.push("");
  lines.push(
    "Generated by `node scripts/gen-status.mjs`. Do not hand-edit — edit `specs/*.md` and " +
      "regenerate (`pnpm status`) instead. `node scripts/gen-status.mjs --check` (what CI runs) " +
      "fails if this file is stale relative to the specs."
  );
  lines.push("");

  const specFiles = [...byFile.keys()].sort();
  if (specFiles.length === 0) {
    lines.push("_No requirements defined yet._");
    lines.push("");
  }

  let totalAll = 0;
  let activeAll = 0;
  let retiredAll = 0;
  let uncitedAll = 0;

  for (const file of specFiles) {
    const reqs = byFile.get(file).sort((a, b) => a.id.localeCompare(b.id));
    const total = reqs.length;
    const active = reqs.filter((r) => r.status === "active").length;
    const retired = reqs.filter((r) => r.status === "retired").length;
    totalAll += total;
    activeAll += active;
    retiredAll += retired;

    lines.push(`## specs/${file}`);
    lines.push("");
    lines.push(`${total} total, ${active} active, ${retired} retired.`);
    lines.push("");
    lines.push("| Requirement | Status | Citing tests | |");
    lines.push("|---|---|---|---|");
    for (const r of reqs) {
      const citing = citations.get(r.id);
      const hasCitations = citing && citing.size > 0;
      if (!hasCitations && r.status === "active") uncitedAll++;
      const citingCell = hasCitations ? [...citing].sort().join("<br>") : "—";
      const uncitedCell = hasCitations ? "" : "⚠ uncited";
      lines.push(`| ${r.id} | ${r.status} | ${citingCell} | ${uncitedCell} |`);
    }
    lines.push("");
  }

  lines.push("## Totals");
  lines.push("");
  lines.push(
    `${totalAll} requirement(s) across ${specFiles.length} spec file(s): ${activeAll} active, ` +
      `${retiredAll} retired, ${uncitedAll} active-and-uncited (⚠).`
  );
  lines.push("");

  return lines.join("\n");
}

function isMain() {
  return process.argv[1] && import.meta.url === `file://${process.argv[1]}`;
}

if (isMain()) {
  const rootDir = process.cwd();
  const content = generateStatus(rootDir);
  const statusPath = join(rootDir, "STATUS.md");
  if (process.argv.includes("--check")) {
    const existing = existsSync(statusPath) ? readFileSync(statusPath, "utf8") : null;
    if (existing !== content) {
      console.error("STATUS.md is stale. Run `node scripts/gen-status.mjs` and commit the result.");
      process.exit(1);
    }
    console.log("STATUS.md is up to date.");
  } else {
    writeFileSync(statusPath, content);
    console.log(`Wrote ${statusPath}`);
  }
}
