#!/usr/bin/env node
// Generates an agent task brief for one or more requirement IDs: the
// requirement's CURRENT text (never a stale copy-paste), its spec file, and
// the ownership.json globs for that spec — so an implementing agent always
// gets what HEAD actually says. See specs/README.md's "Task briefs" section.
//
// Usage: node scripts/gen-brief.mjs RH-001 PC-003 SP-004
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { parseSpecs } from "./check-drift.mjs";

export function generateBrief(rootDir, ids) {
  const { registry } = parseSpecs(join(rootDir, "specs"));
  const ownershipPath = join(rootDir, "specs", "ownership.json");
  const ownership = existsSync(ownershipPath) ? JSON.parse(readFileSync(ownershipPath, "utf8")) : {};
  const ownershipEntries = Object.entries(ownership).filter(([k]) => !k.startsWith("$"));

  const lines = [];
  lines.push(`# Task brief: ${ids.join(", ")}`);
  lines.push("");
  lines.push("_Generated by `node scripts/gen-brief.mjs` from HEAD — always the current requirement text, never a stale copy._");
  lines.push("");

  for (const id of ids) {
    const info = registry.get(id);
    lines.push(`## ${id}`);
    lines.push("");
    if (!info) {
      lines.push("**UNKNOWN requirement ID** — not found in any `specs/*.md` file. STOP and report rather than guessing what it should say.");
      lines.push("");
      continue;
    }
    const specFile = `specs/${info.file}`;
    const globs = ownershipEntries
      .filter(([, sf]) => sf === specFile)
      .map(([glob]) => glob);

    lines.push(`- **Status**: ${info.status}`);
    lines.push(`- **Spec file**: \`${specFile}\` (line ${info.line})`);
    lines.push(`- **Ownership globs**: ${globs.length ? globs.map((g) => `\`${g}\``).join(", ") : "(none registered in specs/ownership.json)"}`);
    lines.push("- **Statement**:");
    lines.push(`  > ${info.statement}`);
    lines.push("");
    if (info.status === "retired") {
      lines.push("  **Warning**: this requirement is retired. Do not implement against it — check the spec file for what superseded it.");
      lines.push("");
    }
  }

  return lines.join("\n");
}

function isMain() {
  return process.argv[1] && import.meta.url === `file://${process.argv[1]}`;
}

if (isMain()) {
  const ids = process.argv.slice(2);
  if (ids.length === 0) {
    console.error("Usage: node scripts/gen-brief.mjs <SPEC-ID...>");
    process.exit(1);
  }
  console.log(generateBrief(process.cwd(), ids));
}
